name: Docker Container Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: walshd/validators
        tags: |
          type=match,pattern=v(.*),group=1
          type=sha

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: walshd
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        pull: true
        push: true
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        platforms: linux/amd64
